'use strict';
const RANK_CHARS='23456789TJQKA',SUIT_CHARS='shdc',CAT_BASE=759375,MAX_SCENARIOS=20000000;
const rankByCard=new Uint8Array(52),suitByCard=new Uint8Array(52),codeToCard=Object.create(null);
for(let r=0;r<13;r++)for(let s=0;s<4;s++){const c=r*4+s;rankByCard[c]=r+2;suitByCard[c]=s;codeToCard[`${RANK_CHARS[r]}${SUIT_CHARS[s]}`]=c;}
const rankCounts=new Uint8Array(15);
function parseCard(code){const c=codeToCard[code];if(c===undefined)throw new Error(`不正なカードです: ${code}`);return c;}
function pack(category,a=0,b=0,c=0,d=0,e=0){return (((((category*15+a)*15+b)*15+c)*15+d)*15+e);}
function straightHigh(mask){for(let h=14;h>=6;h--){const n=(1<<h)|(1<<(h-1))|(1<<(h-2))|(1<<(h-3))|(1<<(h-4));if((mask&n)===n)return h;}const w=(1<<14)|(1<<5)|(1<<4)|(1<<3)|(1<<2);return (mask&w)===w?5:0;}
function topFiveCode(mask){let result=0,count=0;for(let r=14;r>=2;r--)if(mask&(1<<r)){result=result*15+r;if(++count===5)return result;}while(count++<5)result*=15;return result;}
function evaluate7(cards){rankCounts.fill(0);let rankMask=0;const sc=[0,0,0,0],sm=[0,0,0,0];for(const card of cards){const r=rankByCard[card],s=suitByCard[card];rankCounts[r]++;rankMask|=(1<<r);sc[s]++;sm[s]|=(1<<r);}let flushMask=0;for(let s=0;s<4;s++)if(sc[s]>=5){flushMask=sm[s];break;}if(flushMask){const sf=straightHigh(flushMask);if(sf)return pack(8,sf);}let quad=0;for(let r=14;r>=2;r--)if(rankCounts[r]===4){quad=r;break;}if(quad){let k=0;for(let r=14;r>=2;r--)if(r!==quad&&rankCounts[r]){k=r;break;}return pack(7,quad,k);}let trip=0,pairForFull=0;for(let r=14;r>=2;r--){if(!trip&&rankCounts[r]>=3)trip=r;else if(trip&&!pairForFull&&rankCounts[r]>=2){pairForFull=r;break;}}if(trip&&pairForFull)return pack(6,trip,pairForFull);if(flushMask)return 5*CAT_BASE+topFiveCode(flushMask);const straight=straightHigh(rankMask);if(straight)return pack(4,straight);if(trip){const k=[];for(let r=14;r>=2;r--)if(r!==trip&&rankCounts[r])k.push(r);return pack(3,trip,k[0],k[1]);}const pairs=[];for(let r=14;r>=2;r--)if(rankCounts[r]>=2)pairs.push(r);if(pairs.length>=2){let k=0;for(let r=14;r>=2;r--)if(r!==pairs[0]&&r!==pairs[1]&&rankCounts[r]){k=r;break;}return pack(2,pairs[0],pairs[1],k);}if(pairs.length===1){const k=[];for(let r=14;r>=2;r--)if(r!==pairs[0]&&rankCounts[r])k.push(r);return pack(1,pairs[0],k[0],k[1],k[2]);}return topFiveCode(rankMask);}
function choose(n,k){if(k<0||k>n)return 0;if(k===0||k===n)return 1;const m=Math.min(k,n-k);let result=1;for(let i=1;i<=m;i++)result=result*(n-m+i)/i;return Math.round(result);}
function blockedArray(cards){const b=new Uint8Array(52);cards.forEach(c=>b[c]=1);return b;}
function allCombos(blocked){const out=[];for(let a=0;a<51;a++){if(blocked[a])continue;for(let b=a+1;b<52;b++)if(!blocked[b])out.push([a,b]);}return out;}
function handClassCombos(hand,blocked){const ra=RANK_CHARS.indexOf(hand[0]),rb=RANK_CHARS.indexOf(hand[1]),out=[];if(hand.length===2){for(let s1=0;s1<4;s1++)for(let s2=s1+1;s2<4;s2++){const a=ra*4+s1,b=ra*4+s2;if(!blocked[a]&&!blocked[b])out.push([a,b]);}return out;}const suited=hand.endsWith('s');for(let s1=0;s1<4;s1++)for(let s2=0;s2<4;s2++){if(suited&&s1!==s2)continue;if(!suited&&s1===s2)continue;const a=ra*4+s1,b=rb*4+s2;if(!blocked[a]&&!blocked[b])out.push([a,b]);}return out;}
function combosForSpec(spec,blocked){if(spec.type==='fixed'){const cards=spec.cards.map(parseCard);return cards.some(c=>blocked[c])?[]:[cards];}if(spec.type==='random')return allCombos(blocked);const seen=new Set(),out=[];for(const hand of spec.classes||[])for(const combo of handClassCombos(hand,blocked)){const key=combo[0]<combo[1]?`${combo[0]}-${combo[1]}`:`${combo[1]}-${combo[0]}`;if(!seen.has(key)){seen.add(key);out.push(combo);}}return out;}
function boardRunouts(remaining,missing,cb){if(missing===0){cb([]);return;}if(missing===1){for(let a=0;a<remaining.length;a++)cb([remaining[a]]);return;}if(missing===2){for(let a=0;a<remaining.length-1;a++)for(let b=a+1;b<remaining.length;b++)cb([remaining[a],remaining[b]]);return;}if(missing===5){const n=remaining.length;for(let a=0;a<n-4;a++)for(let b=a+1;b<n-3;b++)for(let c=b+1;c<n-2;c++)for(let d=c+1;d<n-1;d++)for(let e=d+1;e<n;e++)cb([remaining[a],remaining[b],remaining[c],remaining[d],remaining[e]]);return;}throw new Error('このボード枚数には対応していません。');}
function createCounter(playerCount,total){return {players:Array.from({length:playerCount},()=>({wins:0,ties:0,equityShare:0})),total,processed:0,nextProgress:0,progressStep:Math.max(1,Math.floor(total/100))};}
function reportProgress(c,force=false){if(!force&&c.processed<c.nextProgress)return;c.nextProgress=c.processed+c.progressStep;self.postMessage({type:'progress',processed:c.processed,total:c.total});}
function recordScenario(players,board,c){const scores=players.map(h=>evaluate7([h[0],h[1],...board])),best=Math.max(...scores),w=[];scores.forEach((s,i)=>{if(s===best)w.push(i)});w.forEach(i=>{if(w.length===1)c.players[i].wins++;else c.players[i].ties++;c.players[i].equityShare+=1/w.length;});c.processed++;reportProgress(c);}
function remainingCards(used){const b=blockedArray(used),out=[];for(let c=0;c<52;c++)if(!b[c])out.push(c);return out;}
function calculate(payload){const board=payload.board.map(parseCard),player3=payload.player3?payload.player3.map(parseCard):null,fixedBase=[...board,...(player3||[])],heroCombos=combosForSpec(payload.heroSpec,blockedArray(fixedBase));if(!heroCombos.length)throw new Error('Player 1の有効な組み合わせがありません。');const missing=5-board.length;let total=0;const pairs=[];for(const hero of heroCombos){const villainCombos=combosForSpec(payload.villainSpec,blockedArray([...fixedBase,...hero]));for(const villain of villainCombos){const used=[...board,...hero,...villain,...(player3||[])];if(new Set(used).size!==used.length)continue;const runouts=choose(52-used.length,missing);total+=runouts;if(total>MAX_SCENARIOS)throw new Error('CALCULATION_TOO_LARGE');pairs.push({hero,villain,used});}}if(!total)throw new Error('有効なカード組み合わせがありません。');const counter=createCounter(player3?3:2,total);for(const pair of pairs){const remaining=remainingCards(pair.used);boardRunouts(remaining,missing,runout=>recordScenario(player3?[pair.hero,pair.villain,player3]:[pair.hero,pair.villain],[...board,...runout],counter));}reportProgress(counter,true);return counter;}
self.onmessage=event=>{try{const c=calculate(event.data),ht=event.data.heroSpec.type,vt=event.data.villainSpec.type,modeLabel=event.data.player3?'3人ポット・指定ハンド':`${ht==='range'?'Player 1レンジ':'Player 1指定'} vs ${vt==='range'?'Player 2レンジ':vt==='random'?'ランダム':'指定ハンド'}`;self.postMessage({type:'result',players:c.players,total:c.total,modeLabel});}catch(error){self.postMessage({type:'error',code:error.message,message:error.message});}};
